spring:
    application:
        name: demo
    jpa:
        show-sql: true
    datasource:
        url: jdbc:mysql://localhost:3306/companydb
        username: seng2050_admin
        password: P@ssword

